package com.tomandy.oneclaw.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightPrimary = Color(0xFF3D5AFE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE1FF)
val LightOnPrimaryContainer = Color(0xFF00105C)
val LightSecondary = Color(0xFF5C6BC0)
val LightSecondaryContainer = Color(0xFFE0E1F5)
val LightOnSecondaryContainer = Color(0xFF1A1F4B)
val LightTertiary = Color(0xFF00897B)
val LightTertiaryContainer = Color(0xFFB2DFDB)
val LightOnTertiaryContainer = Color(0xFF00352F)
val LightBackground = Color(0xFFF5F5F7)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF0F0F5)
val LightSurfaceContainerHigh = Color(0xFFECEDF4)
val LightSurfaceContainerHighest = Color(0xFFE4E5ED)
val LightOnBackground = Color(0xFF1A1A2E)
val LightOnSurface = Color(0xFF1A1A2E)
val LightOnSurfaceVariant = Color(0xFF5F6368)
val LightOutline = Color(0xFFC4C7D0)
val LightOutlineVariant = Color(0xFFE2E5EC)
val LightError = Color(0xFFD32F2F)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFDECEA)
val LightOnErrorContainer = Color(0xFF410002)

// Dark theme colors
val DarkPrimary = Color(0xFFB3C4FF)
val DarkOnPrimary = Color(0xFF002387)
val DarkPrimaryContainer = Color(0xFF2941C1)
val DarkOnPrimaryContainer = Color(0xFFDEE1FF)
val DarkSecondary = Color(0xFFC0C6FF)
val DarkSecondaryContainer = Color(0xFF3F4999)
val DarkOnSecondaryContainer = Color(0xFFE0E1F5)
val DarkTertiary = Color(0xFF80CBC4)
val DarkTertiaryContainer = Color(0xFF005048)
val DarkOnTertiaryContainer = Color(0xFFB2DFDB)
val DarkBackground = Color(0xFF121218)
val DarkSurface = Color(0xFF1E1E2A)
val DarkSurfaceVariant = Color(0xFF282836)
val DarkSurfaceContainerHigh = Color(0xFF2E2E3E)
val DarkSurfaceContainerHighest = Color(0xFF363646)
val DarkOnBackground = Color(0xFFE4E4F0)
val DarkOnSurface = Color(0xFFE4E4F0)
val DarkOnSurfaceVariant = Color(0xFF9E9EAE)
val DarkOutline = Color(0xFF555566)
val DarkOutlineVariant = Color(0xFF3A3A4A)
val DarkError = Color(0xFFFF8A80)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Semantic colors
val SuccessGreen = Color(0xFF2E7D32)
